FROM bitnami/keycloak:22.0.5
WORKDIR /opt/bitnami/keycloak

COPY ./denhaagtheme/ themes/denhaagtheme/
COPY ./IdentityProviderAttributeSessionNoteMapper-1.0-SNAPSHOT.jar providers/


# FROM quay.io/keycloak/keycloak:22.0 as builder
# ENV KC_HEALTH_ENABLED=true
# ENV KC_METRICS_ENABLED=true
# ENV KC_FEATURES=token-exchange,admin-fine-grained-authz
# ENV KC_DB=postgres
# # need relative path for old test environment
# # ENV KC_HTTP_RELATIVE_PATH=/auth

# COPY ./IdentityProviderAttributeSessionNoteMapper-1.0-SNAPSHOT.jar /opt/keycloak/providers/

# RUN /opt/keycloak/bin/kc.sh build

# FROM quay.io/keycloak/keycloak:22.0
# WORKDIR /opt/keycloak
# ENV KC_LOG_LEVEL=INFO
# ENV KC_PROXY=edge
# # ENV KC_HTTP_ENABLED=true
# # ENV KC_HOSTNAME_STRICT=false
# # ENV KC_HOSTNAME_STRICT_HTTPS=false

# COPY --from=builder /opt/keycloak/lib/quarkus/ lib/quarkus/
# COPY --from=builder /opt/keycloak/providers/ providers/

# # COPY ./keycloakdhzgwpubliek/ themes/keycloakdhzgwpubliek/
# COPY ./denhaagtheme/ themes/denhaagtheme/

# COPY java.config /etc/crypto-policies/back-ends/


# ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start","--optimized"]